name: unit tests

on:
  push:
    branches-ignore: [main]
  workflow_dispatch:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
      # https://github.com/actions/setup-node/releases/tag/v3.8.1
        uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d
        with:
          node-version: lts/*
          registry-url: 'https://registry.npmjs.org'
          cache: npm
      - name: Install dependencies
        run: npm install
      - name: Run unit tests
        run: npm run test
